# Generated by Django 4.2.10 on 2024-04-13 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="answer",
            new_name="text",
        ),
    ]
