# Generated by Django 4.2.10 on 2024-04-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_text_question_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="answer_images/"),
        ),
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="question_images/"
            ),
        ),
    ]
